# Generated by Django 4.2.27 on 2026-02-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='qualityassurance',
            constraint=models.UniqueConstraint(fields=('player', 'quality'), name='uq_player_quality'),
        ),
    ]
