# Generated by Django 4.2.27 on 2026-02-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_qualityassurance_uq_player_quality'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qualityassurance',
            name='uq_player_quality',
        ),
        migrations.AddField(
            model_name='player',
            name='additional_burnout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='commendations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='demerits',
            field=models.IntegerField(default=0),
        ),
    ]
