# Generated by Django 4.2.27 on 2026-02-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_qualityassurance_uq_player_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='anomaly_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='competency_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='max_anomaly_level',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='player',
            name='max_competency_level',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='player',
            name='max_reality_level',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='player',
            name='reality_level',
            field=models.IntegerField(default=0),
        ),
    ]
