# Generated by Django 4.2.27 on 2026-03-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_player_anomaly_level_player_competency_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualityassurance",
            name="available_qas",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="qualityassurance",
            name="max_qas",
            field=models.IntegerField(default=0),
        ),
    ]
