# Generated by Django 4.2.27 on 2026-01-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('anomaly', models.CharField(blank=True, max_length=255)),
                ('reality', models.CharField(blank=True, max_length=255)),
                ('competency', models.CharField(blank=True, max_length=255)),
                ('requisition', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PowerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_question_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('power_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='triangle_agency_server.powerquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_id', models.IntegerField(unique=True)),
                ('success', models.TextField(blank=True)),
                ('extra_success', models.TextField(blank=True)),
                ('fail', models.TextField(blank=True)),
                ('power_questions', models.ManyToManyField(blank=True, related_name='powers', to='triangle_agency_server.powerquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(blank=True, max_length=255)),
                ('uses', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='triangle_agency_server.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='powers',
            field=models.ManyToManyField(blank=True, related_name='players', to='triangle_agency_server.power'),
        ),
        migrations.AddField(
            model_name='player',
            name='reality_connection_power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_reality_connection', to='triangle_agency_server.power'),
        ),
        migrations.CreateModel(
            name='MissionPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaos_pool', models.IntegerField(default=0)),
                ('loose_ends', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public', to='triangle_agency_server.mission')),
            ],
        ),
        migrations.CreateModel(
            name='MissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(blank=True, max_length=50)),
                ('asset_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('mission_public', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='triangle_agency_server.missionpublic')),
            ],
        ),
        migrations.CreateModel(
            name='MissionGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.JSONField(blank=True, default=list)),
                ('player_notes', models.JSONField(blank=True, default=dict)),
                ('player_signals', models.JSONField(blank=True, default=dict)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gm', to='triangle_agency_server.mission')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='missions', to='triangle_agency_server.player'),
        ),
    ]
