# Generated by Django 4.2.27 on 2026-02-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.TextField()),
                ('chaos_pool', models.IntegerField(default=0)),
                ('loose_ends', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.TextField(choices=[('Attentiveness', 'Attentiveness'), ('Duplicity', 'Duplicity'), ('Dynamism', 'Dynamism'), ('Empathy', 'Empathy'), ('Initiative', 'Initiative'), ('Persistence', 'Persistence'), ('Presence', 'Presence'), ('Professionalism', 'Professionalism'), ('Subtlety', 'Subtlety')], default='Attentiveness')),
                ('available_qas', models.IntegerField(default=0)),
                ('max_qas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(blank=True)),
                ('missions', models.ManyToManyField(to='triangle_agency_server.mission')),
                ('qas', models.ManyToManyField(to='triangle_agency_server.qualityassurance')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='players',
            field=models.ManyToManyField(to='triangle_agency_server.player'),
        ),
    ]
