# Generated by Django 4.2.27 on 2026-01-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_agency_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerqa',
            name='player',
        ),
        migrations.RemoveField(
            model_name='power',
            name='power_questions',
        ),
        migrations.RemoveField(
            model_name='powerquestionanswer',
            name='power_question',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='players',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerQA',
        ),
        migrations.DeleteModel(
            name='Power',
        ),
        migrations.DeleteModel(
            name='PowerQuestion',
        ),
        migrations.DeleteModel(
            name='PowerQuestionAnswer',
        ),
    ]
