# Generated by Django 4.2.27 on 2026-01-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_agency_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='game_id',
            new_name='mission_id',
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_name',
            field=models.TextField(blank=True),
        ),
    ]
