# Generated by Django 4.2.27 on 2026-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_agency_server', '0002_remove_playerqa_player_remove_power_power_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('available_qas', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='missionimage',
            name='mission_public',
        ),
        migrations.RemoveField(
            model_name='missionpublic',
            name='mission',
        ),
        migrations.AddField(
            model_name='mission',
            name='chaos_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='loose_ends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='MissionGM',
        ),
        migrations.DeleteModel(
            name='MissionImage',
        ),
        migrations.DeleteModel(
            name='MissionPublic',
        ),
        migrations.AddField(
            model_name='player',
            name='mission',
            field=models.ManyToManyField(to='triangle_agency_server.mission'),
        ),
        migrations.AddField(
            model_name='player',
            name='qas',
            field=models.ManyToManyField(to='triangle_agency_server.qualityassurance'),
        ),
    ]
