# Generated by Django 4.2.27 on 2026-02-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_agency_server', '0003_player_qualityassurance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='mission',
            new_name='missions',
        ),
        migrations.AddField(
            model_name='mission',
            name='players',
            field=models.ManyToManyField(to='triangle_agency_server.player'),
        ),
    ]
