# Generated by Django 4.2.27 on 2026-02-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_agency_server', '0004_rename_mission_player_missions_mission_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityassurance',
            name='name',
        ),
        migrations.AddField(
            model_name='qualityassurance',
            name='max_qas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityassurance',
            name='quality',
            field=models.TextField(choices=[('Attentiveness', 'Attentiveness'), ('Duplicity', 'Duplicity'), ('Dynamism', 'Dynamism'), ('Empathy', 'Empathy'), ('Initiative', 'Initiative'), ('Persistence', 'Persistence'), ('Presence', 'Presence'), ('Professionalism', 'Professionalism'), ('Subtlety', 'Subtlety')], default='Attentiveness'),
        ),
    ]
